# Generated by Django 4.1.7 on 2023-06-24 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='色(16進数)')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル')),
                ('description', models.TextField(verbose_name='説明文')),
                ('main_text', mdeditor.fields.MDTextField(verbose_name='本文')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHubリンク')),
                ('site_link', models.URLField(blank=True, null=True, verbose_name='サイトリンク')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.category', verbose_name='カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, to='works.tag', verbose_name='タグ')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
