# Generated by Django 4.1.7 on 2023-06-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='github_link',
            new_name='githubLink',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='site_link',
            new_name='siteLink',
        ),
    ]
